// <auto-generated />
using System;
using CMCS.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMCS.WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023112802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CMCS.WebApp.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<int>("LecturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Period")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            HoursWorked = 40m,
                            LecturerId = 1,
                            Period = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 550m,
                            Status = "Submitted",
                            SubmitDate = new DateTime(2025, 10, 21, 13, 27, 46, 14, DateTimeKind.Local).AddTicks(5117)
                        },
                        new
                        {
                            ClaimId = 2,
                            HoursWorked = 35m,
                            LecturerId = 1,
                            Period = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProcessedBy = "Sarah Coordinator",
                            ProcessedDate = new DateTime(2025, 9, 28, 13, 27, 46, 14, DateTimeKind.Local).AddTicks(5135),
                            Rate = 550m,
                            Status = "Approved",
                            SubmitDate = new DateTime(2025, 9, 23, 13, 27, 46, 14, DateTimeKind.Local).AddTicks(5134)
                        });
                });

            modelBuilder.Entity("CMCS.WebApp.Models.SupportingDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClaimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId");

                    b.ToTable("SupportingDocuments");
                });

            modelBuilder.Entity("CMCS.WebApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateRegistered = new DateTime(2025, 10, 23, 13, 27, 46, 14, DateTimeKind.Local).AddTicks(4829),
                            Email = "lecturer@cmcs.com",
                            IsActive = true,
                            Name = "John Lecturer",
                            Password = "password",
                            Role = "Lecturer"
                        },
                        new
                        {
                            UserId = 2,
                            DateRegistered = new DateTime(2025, 10, 23, 13, 27, 46, 14, DateTimeKind.Local).AddTicks(4841),
                            Email = "coordinator@cmcs.com",
                            IsActive = true,
                            Name = "Sarah Coordinator",
                            Password = "password",
                            Role = "Coordinator"
                        },
                        new
                        {
                            UserId = 3,
                            DateRegistered = new DateTime(2025, 10, 23, 13, 27, 46, 14, DateTimeKind.Local).AddTicks(4845),
                            Email = "manager@cmcs.com",
                            IsActive = true,
                            Name = "Mike Manager",
                            Password = "password",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("CMCS.WebApp.Models.Claim", b =>
                {
                    b.HasOne("CMCS.WebApp.Models.User", "Lecturer")
                        .WithMany("Claims")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CMCS.WebApp.Models.SupportingDocument", b =>
                {
                    b.HasOne("CMCS.WebApp.Models.Claim", "Claim")
                        .WithMany("SupportingDocuments")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("CMCS.WebApp.Models.Claim", b =>
                {
                    b.Navigation("SupportingDocuments");
                });

            modelBuilder.Entity("CMCS.WebApp.Models.User", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
